services:
  ayder:
    build: .
    container_name: ayder
    shm_size: 2g
    ports:
      - "1109:1109"
    ipc: shareable
    ulimits:
      memlock:
        soft: -1
        hard: -1
    security_opt:
      - seccomp:unconfined
    volumes:
      - ayder_data:/data
    restart: unless-stopped


volumes:
  ayder_data:

