global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ramforge'
    metrics_path: /metrics
    static_configs:
      - targets: ['ramforge:1109']

rule_files:
  - /etc/prometheus/alerts.yml

